### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by davidrosenberg** [davidrosenberg/ml2015#36]
I pushed some changes last night, worked locally, but travis crashes and I can't really figure out what I broke.

[05:57:12] Using gulpfile ~/build/davidrosenberg/ml2015/gulpfile.js
[05:57:12] Starting 'template'...
[05:57:12] 'template' errored after 9.63 ms
[05:57:12] TypeError: Object.keys called on non-object
    at keys (native)
    at Function.keys (/home/travis/build/davidrosenberg/ml2015/node_modules/traceur/bin/traceur.js:151:29)
    at /home/travis/build/davidrosenberg/ml2015/build/templater.js:44:18
    at Array.forEach (native)
    at $__3 (/home/travis/build/davidrosenberg/ml2015/build/templater.js:37:35)
    at parseDocuments (/home/travis/build/davidrosenberg/ml2015/build/@traceur/generated/TemplateParser/9:6:65)
    at $__default (/home/travis/build/davidrosenberg/ml2015/build/templater.js:21:23)
    at Gulp.<anonymous> (/home/travis/build/davidrosenberg/ml2015/gulpfile.js:14:5)
    at module.exports (/home/travis/build/davidrosenberg/ml2015/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/travis/build/davidrosenberg/ml2015/node_modules/gulp/node_modules/orchestrator/index.js:273:3)

**Comment by domenic** [comment]
OK, hopefully we have enough mitigation strategies in place to prevent this in the future.

You'll need to do `npm install` and re-start the watcher after pulling down my latest changes.
